public interface Animal {
    public void walk();
    public void run();
    public void eat();
    public void sleep();
    public void crawl();
    public void roar();
    public void growl();
    public void look();
    public void jump();
    public void attack();
    public void bite();
    public void sprint();
    public void nap();
    public void giveBirth();
    public void hibernate();
    public void scratch();
    public void sneak();
    public void pound();
    public void fly();
    public void tackle();
    public void swim();
    public void layEgg();
    public void aggro();
    public void poison();
    public void dive();
    public void crush();
    public void cut();
}
